server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://ai-db:5432/ai_db
    username: ai_user
    password: ai_pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  ai:
    ollama:
      base-url: http://ollama:11434
      chat:
        model: mistral
      embedding:
        model: nomic-embed-text
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: ai-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer