spring:
  datasource:
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,refresh,metrics
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"