server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://transaction-db:5432/transaction_db
    username: transaction_user
    password: transaction_pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer